[[beans-introduction]]
= 스프링 IoC 컨테이너와 빈(Bean) 소개

이 챕터에서는 IoC(제어의 역전) 원칙에 대한 스프링 프레임워크의 구현을 다룹니다.
DI(의존성 주입)는 IoC의 특수한 형태로, 객체는 오직 생성자의 인자, 팩토리 메서드의 인자,
또는 생성자 또는 팩토리 메서드로 인해 이미 객체 인스턴스로 생성된 이후에 설정할 프로퍼티 값 등을
통해서 객체 간의 의존성(서로 상호작용하는 또 다른 객체들)이 정의됩니다.
그러면 IoC 컨테이너는 빈을 생성할 때 이 의존성을 주입합니다.
이 과정은 근본적으로 빈 자체가 스스로 인스턴스화를 제어하거나, 직접 클래스를 생성하여 자신과 연관된 의존성을 다루거나
또는 서비스 로케이터 패턴과 같은 메커니즘을 역전(말그대로, 제어의 역전)하는 것입니다.

`org.springframework.beans`과 `org.springframework.context` 패키지는
스프링 IoC 컨테이너를 위한 기본 패키지입니다.
{spring-framework-api}/beans/factory/BeanFactory.html[`BeanFactory`] 인터페이스는
어떤 타입도 다룰 수 있는 고도화된 설정 메커니즘을 제공합니다.
{spring-framework-api}/context/ApplicationContext.html[`ApplicationContext`]는
`BeanFactory`의 하위 인터페이스입니다. 이는 다음과 같은 기능을 추가합니다.

* 스프링의 AOP 기능과의 손쉬운 통합
* 메시지 리소스 처리 (국제화를 위해 사용할 수 있음)
* 이벤트 발행
* 웹 애플리케이션 사용을 위한 `WebApplicationContext`와 같은 애플리케이션 계층 특화 컨텍스트

즉, `BeanFactory`는 설정 프레임워크와 기본적인 기능을 제공하고,
`ApplicationContext`는 좀 더 엔터프라이즈에 특화된 기능이 추가되었습니다.
`ApplicationContext`는 완전한 `BeanFactory`의 상위 집합이며,
이 챕터에서는 스프링의 IoC 컨테이너에 대한 설명에 한해서만 `ApplicationContext`를 사용합니다.
`ApplicationContext` 대신 `BeanFactory`를 사용하는 방법에 대해서는
xref:core/beans/beanfactory.adoc[`BeanFactory` API] 섹션을 참고하세요.

스프링에서는 애플케이션의 근간을 이루고 스프링 IoC 컨테이너로부터 관리되는 모든 객체를 빈(Bean)이라고 합니다.
빈은 스프링 IoC 컨테이너에 의해 인스턴스화되고 조립되며 관리되는 객체입니다.
이를 제외하면 빈은 단순히 애플리케이션의 많은 객체 중 하나일 뿐입니다.
빈과 그들 사이의 의존성은 컨테이너가 사용하는 설정 메타데이터에 반영됩니다.


