[[overview]]
= 스프링 프레임워크 개요
:docinfo1:

스프링은 Java 엔터프라이즈 애플리케이션을 쉽게 만들 수 있습니다. 이는 엔터프라이즈 환경에서 Java를 도입하기 위해
필요한 모든 것을 제공하며, JVM 위에서 동작하는 또 다른 언어인 Kotlin과 Groovy도 지원합니다. 또한, 애플리케이션이
필요로하는 많은 종류의 아키텍처들을 만들 수 있는 유연성을 가지고 있습니다. 스프링 프레임워크 6.0을 사용하기 위해서는
Java 17+ 버전이 필요합니다.

스프링은 다양한 애플리케이션 시나리오를 지원합니다. 거대한 크기의 엔터프라이즈에서 애플리케이션은 종종 오랜기간동안
존재하고 있고 개발자가 제어할 수 없는 업그레이드 주기를 갖는 JDK와 애플s리케이션 서버 위에서 동작해야합니다.
다른 애플리케이션은 내장 서버가 있는 단일 JAR에서 동작하고, 이는 클라우드 환경에서 실행될 수 있습니다.
심지어 서버가 필요없는 독립 실행형 어플리케이션(예를들어, 배치나 통합 워크로드)이 되어야 할 수도 있습니다.

스프링은 오픈 소스이고, 크고 활성화된 커뮤니티를 갖고 있습니다. 여기서 실제로 사용된 다양한 케이스를 바탕으로 지속적인
피드백을 제공하고 있습니다. 이 덕분에 스프링은 오랜 기간동안 성공적으로 발전하고 있습니다.


[[overview-spring]]
== "Spring" 의미

"Spring" 이라는 용어는 여러 상황에서 다른 의미로 사용됩니다. 이는 모든 것이 시작된 스프링 프레임워크 프로젝트 자체를 지칭할 수 있습니다.
시간이 지나 다른 스프링 프로젝트들은 스프링 프레임워크 위에 만들어졌습니다. 대부분, 사람들이 "Spring" 이라고 말하면,
이는 연관된 전체 프로젝트를 의미합니다. 이 문서에서는 스프링 프레임워크 그 자체를 기준으로 초점을 맞추고 있습니다.

스프링 프레임워크는 여러 모듈로 나눠져있습니다. 애플리케이션은 필요한 모듈을 선택할 수 있습니다.
핵심 컨테이너 모듈에는 구성 모델과 의존성 주입 메커니즘이 포함되어 있습니다. 
그 외에도 스프링 프레임워크는 메시징, 트랜잭션 데이터 및 지속성, 웹을 비롯한 다양한 애플리케이션 아키텍처에 대한
기본적인 지원을 제공합니다. 또한 서블릿을 기반한 Spring MVC 웹 프레임워크와 리액티브 웹 프레임워크인
Spring WebFlux도 포함되어 있습니다.

모듈에 관한 참고 사항: Spring의 프레임워크 JAR 파일은 JDK 9의 모듈 경로("Jigsaw")에 배포할 수 있도록 허용됩니다. 
JDK 9에서 모듈을 사용하는 애플리케이션에서 Spring Framework 5 JAR 파일은 "Automatic-Module-Name" 매니페스트 항목을 포함하고 있습니다. 
이 항목은 안정적인 언어 수준의 모듈 이름("spring.core", "spring.context" 등)을 정의하며, JAR 아티팩트 이름과는 독립적입니다 
(JAR 파일은 같은 네이밍 패턴을 따르지만 "." 대신 "-"을 사용합니다. 예: "spring-core" 및 "spring-context"). 
물론, Spring의 프레임워크 JAR 파일은 JDK 8 및 9+에서 모두 클래스패스에서 정상적으로 작동합니다.


[[overview-history]]
== 스프링과 스프링 프레임워크 역사

스프링은 2003년, https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition[J2EE] 명세의 복잡성에 대한 응답으로 탄생하였습니다.
일부는 Java EE와 현대 이 후속인 Jakarta EE가 스프링과 경쟁을 하고 있다고 여기지만, 사실 이 둘은 서로 상호 보완적입니다.
스프링 프로그래밍 모델은 Jakarta EE 플랫폼 명세를 도입하기보다는 
오히려 전통적인 EE 범주에서 신중하게 선택된 각각의 명세를 통합하였습니다.

* Servlet API ({JSR}340[JSR 340])
* WebSocket API ({JSR}356[JSR 356])
* Concurrency Utilities ({JSR}236[JSR 236])
* JSON Binding API ({JSR}367[JSR 367])
* Bean Validation ({JSR}303[JSR 303])
* JPA ({JSR}338[JSR 338])
* JMS ({JSR}914[JSR 914])
* as well as JTA/JCA setups for transaction coordination, if necessary.

또한, 스프링 프레임워크는 의존성 주입({JSR}330[JSR 330])과 공통 애노테이션({JSR}250[JSR 250]) 명세를 지원합니다.
이는 애플리케이션 개발자가 스프링 프레임워크에서 제공된 스프링의 특정 기술 대신 사용할 수 있습니다.
초기에는, 이러한 명세가 `javax` 라는 공통 자바 패키지에 있었습니다.

스프링 프레임워크 6.0에서는 Jakarta EE 9 수준(예: Servlet 5.0+, JPA 3.0+)으로 업그레이드 되었습니다.
기존의 `javax` 패키지 대신 `jakarta` 라는 네임스페이스를 기반으로 합니다.
최소한 EE 9이고 이미 EE 10 수준을 지원하는 스프링은 Jakarta EE API의 추가 발전에 대해서
즉각적으로 지원할 수 있도록 준비하고 있습니다.
스프링 프레임워크 6.0은 Tomcat 10.1, Jetty 11, Undertow 2.3과 같은 웹 서버와 Hibernate ORM 6.1과 완벽하게 호환됩니다.


Over time, the role of Java/Jakarta EE in application development has evolved. In the
early days of J2EE and Spring, applications were created to be deployed to an application
server. Today, with the help of Spring Boot, applications are created in a devops- and
cloud-friendly way, with the Servlet container embedded and trivial to change. As of
Spring Framework 5, a WebFlux application does not even use the Servlet API directly
and can run on servers (such as Netty) that are not Servlet containers.

Spring continues to innovate and to evolve. Beyond the Spring Framework, there are other
projects, such as Spring Boot, Spring Security, Spring Data, Spring Cloud, Spring Batch,
among others. It’s important to remember that each project has its own source code repository,
issue tracker, and release cadence. See {spring-site-projects}[spring.io/projects] for
the complete list of Spring projects.




[[overview-philosophy]]
== Design Philosophy

When you learn about a framework, it’s important to know not only what it does but what
principles it follows. Here are the guiding principles of the Spring Framework:

* Provide choice at every level. Spring lets you defer design decisions as late as possible.
For example, you can switch persistence providers through configuration without changing
your code. The same is true for many other infrastructure concerns and integration with
third-party APIs.
* Accommodate diverse perspectives. Spring embraces flexibility and is not opinionated
about how things should be done. It supports a wide range of application needs with
different perspectives.
* Maintain strong backward compatibility. Spring’s evolution has been carefully managed
to force few breaking changes between versions. Spring supports a carefully chosen range
of JDK versions and third-party libraries to facilitate maintenance of applications and
libraries that depend on Spring.
* Care about API design. The Spring team puts a lot of thought and time into making APIs
that are intuitive and that hold up across many versions and many years.
* Set high standards for code quality. The Spring Framework puts a strong emphasis on
meaningful, current, and accurate javadoc. It is one of very few projects that can claim
clean code structure with  no circular dependencies between packages.




[[overview-feedback]]
== Feedback and Contributions

For how-to questions or diagnosing or debugging issues, we suggest using Stack Overflow. Click
{stackoverflow-spring-tag}+or+spring-mvc+or+spring-aop+or+spring-jdbc+or+spring-r2dbc+or+spring-transactions+or+spring-annotations+or+spring-jms+or+spring-el+or+spring-test+or+spring+or+spring-orm+or+spring-jmx+or+spring-cache+or+spring-webflux+or+spring-rsocket?tab=Newest[here]
for a list of the suggested tags to use on Stack Overflow. If you're fairly certain that
there is a problem in the Spring Framework or would like to suggest a feature, please use
the {spring-framework-issues}[GitHub Issues].

If you have a solution in mind or a suggested fix, you can submit a pull request on
{spring-framework-github}[Github]. However, please keep in mind
that, for all but the most trivial issues, we expect a ticket to be filed in the issue
tracker, where discussions take place and leave a record for future reference.

For more details see the guidelines at the {spring-framework-code}/CONTRIBUTING.md[CONTRIBUTING],
top-level project page.




[[overview-getting-started]]
== Getting Started

If you are just getting started with Spring, you may want to begin using the Spring
Framework by creating a {spring-site-projects}/spring-boot/[Spring Boot]-based
application. Spring Boot provides a quick (and opinionated) way to create a
production-ready Spring-based application. It is based on the Spring Framework, favors
convention over configuration, and is designed to get you up and running as quickly
as possible.

You can use https://start.spring.io/[start.spring.io] to generate a basic project or follow
one of the {spring-site-guides}["Getting Started" guides], such as
{spring-site-guides}/gs/rest-service/[Getting Started Building a RESTful Web Service].
As well as being easier to digest, these guides are very task focused, and most of them
are based on Spring Boot. They also cover other projects from the Spring portfolio that
you might want to consider when solving a particular problem.
