[[overview]]
= 스프링 프레임워크 개요
:docinfo1:

스프링은 Java 엔터프라이즈 애플리케이션을 쉽게 만들 수 있습니다. 이는 엔터프라이즈 환경에서 Java를 도입하기 위해
필요한 모든 것을 제공하며, JVM 위에서 동작하는 또 다른 언어인 Kotlin과 Groovy도 지원합니다. 또한, 애플리케이션이
필요로하는 많은 종류의 아키텍처들을 만들 수 있는 유연성을 가지고 있습니다. 스프링 프레임워크 6.0을 사용하기 위해서는
Java 17+ 버전이 필요합니다.

스프링은 다양한 애플리케이션 시나리오를 지원합니다. 거대한 크기의 엔터프라이즈에서 애플리케이션은 종종 오랜기간동안
존재하고 있고 개발자가 제어할 수 없는 업그레이드 주기를 갖는 JDK와 애플s리케이션 서버 위에서 동작해야합니다.
다른 애플리케이션은 내장 서버가 있는 단일 JAR에서 동작하고, 이는 클라우드 환경에서 실행될 수 있습니다.
심지어 서버가 필요없는 독립 실행형 어플리케이션(예를들어, 배치나 통합 워크로드)이 되어야 할 수도 있습니다.

스프링은 오픈 소스이고, 크고 활성화된 커뮤니티를 갖고 있습니다. 여기서 실제로 사용된 다양한 케이스를 바탕으로 지속적인
피드백을 제공하고 있습니다. 이 덕분에 스프링은 오랜 기간동안 성공적으로 발전하고 있습니다.


[[overview-spring]]
== "Spring" 의미

"Spring" 이라는 용어는 여러 상황에서 다른 의미로 사용됩니다. 이는 모든 것이 시작된 스프링 프레임워크 프로젝트 자체를 지칭할 수 있습니다.
시간이 지나 다른 스프링 프로젝트들은 스프링 프레임워크 위에 만들어졌습니다. 대부분, 사람들이 "Spring" 이라고 말하면,
이는 연관된 전체 프로젝트를 의미합니다. 이 문서에서는 스프링 프레임워크 그 자체를 기준으로 초점을 맞추고 있습니다.

스프링 프레임워크는 여러 모듈로 나눠져있습니다. 애플리케이션은 필요한 모듈을 선택할 수 있습니다.
핵심 컨테이너 모듈에는 구성 모델과 의존성 주입 메커니즘이 포함되어 있습니다. 
그 외에도 스프링 프레임워크는 메시징, 트랜잭션 데이터 및 지속성, 웹을 비롯한 다양한 애플리케이션 아키텍처에 대한
기본적인 지원을 제공합니다. 또한 서블릿을 기반한 Spring MVC 웹 프레임워크와 리액티브 웹 프레임워크인
Spring WebFlux도 포함되어 있습니다.

모듈에 관한 참고 사항: Spring의 프레임워크 JAR 파일은 JDK 9의 모듈 경로("Jigsaw")에 배포할 수 있도록 허용됩니다. 
JDK 9에서 모듈을 사용하는 애플리케이션에서 Spring Framework 5 JAR 파일은 "Automatic-Module-Name" 매니페스트 항목을 포함하고 있습니다. 
이 항목은 안정적인 언어 수준의 모듈 이름("spring.core", "spring.context" 등)을 정의하며, JAR 아티팩트 이름과는 독립적입니다 
(JAR 파일은 같은 네이밍 패턴을 따르지만 "." 대신 "-"을 사용합니다. 예: "spring-core" 및 "spring-context"). 
물론, Spring의 프레임워크 JAR 파일은 JDK 8 및 9+에서 모두 클래스패스에서 정상적으로 작동합니다.


[[overview-history]]
== 스프링과 스프링 프레임워크 역사

스프링은 2003년, https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition[J2EE] 명세의 복잡성에 대한 응답으로 탄생하였습니다.
일부는 Java EE와 현대 이 후속인 Jakarta EE가 스프링과 경쟁을 하고 있다고 여기지만, 사실 이 둘은 서로 상호 보완적입니다.
스프링 프로그래밍 모델은 Jakarta EE 플랫폼 명세를 도입하기보다는 
오히려 전통적인 EE 범주에서 신중하게 선택된 각각의 명세를 통합하였습니다.

* Servlet API ({JSR}340[JSR 340])
* WebSocket API ({JSR}356[JSR 356])
* Concurrency Utilities ({JSR}236[JSR 236])
* JSON Binding API ({JSR}367[JSR 367])
* Bean Validation ({JSR}303[JSR 303])
* JPA ({JSR}338[JSR 338])
* JMS ({JSR}914[JSR 914])
* as well as JTA/JCA setups for transaction coordination, if necessary.

또한, 스프링 프레임워크는 의존성 주입({JSR}330[JSR 330])과 공통 애노테이션({JSR}250[JSR 250]) 명세를 지원합니다.
이는 애플리케이션 개발자가 스프링 프레임워크에서 제공된 스프링의 특정 기술 대신 사용할 수 있습니다.
초기에는, 이러한 명세가 `javax` 라는 공통 자바 패키지에 있었습니다.

스프링 프레임워크 6.0에서는 Jakarta EE 9 수준(예: Servlet 5.0+, JPA 3.0+)으로 업그레이드 되었습니다.
기존의 `javax` 패키지 대신 `jakarta` 라는 네임스페이스를 기반으로 합니다.
최소한 EE 9이고 이미 EE 10 수준을 지원하는 스프링은 Jakarta EE API의 추가 발전에 대해서
즉각적으로 지원할 수 있도록 준비하고 있습니다.
스프링 프레임워크 6.0은 Tomcat 10.1, Jetty 11, Undertow 2.3과 같은 웹 서버와 Hibernate ORM 6.1과 완벽하게 호환됩니다.

시간이 지나, 애플리케이션 개발에서 Java/Jakarta EE의 역할은 발전하였습니다.
J2EE와 스프링 초기에는 애플리케이션이 애플리케이션 서버에 배포되도록 만들어졌습니다.
현재는 스프링 부트의 도움으로 애플리케이션은 데브옵스와 클라우드 친화적인 방식으로 만들어지며,
서블릿 컨테이너가 내장되어 있고 변경하기 쉽습니다.
스프링 프레임워크 5부터는 WebFlux 애플리케이션은 더이상 서블릿 API를 직접 사용하지 않으며,
서블릿 컨테이너가 아닌 서버(Netty와 같은)에서 실행될 수 있습니다.

스프링은 계속해서 혁신하고 발전하고 있습니다. 스프링 프레임워크 이상으로 여기에는 스프링 부트, 스프링 시큐리티,
스프링 데이터, 스프링 클라우드, 스프링 배치 등의 다른 프로젝트가 있습니다.
여기서 중요한 점은 각 프로젝트는 자체 소스 코드 저장소, 이슈 트래커, 그리고 릴리즈 주기를 갖고 있다는 것을 기억하는 것입니다.
{spring-site-projects}[spring.io/projects]에서 전체 스프링 프로젝트를 확인할 수 있습니다.


[[overview-philosophy]]
== 디자인 철학

프레임워크를 배울 때, 그것이 무엇을 하는지 뿐만 아니라 어떤 원칙을 따르는지 아는 것이 중요합니다.
스프링 프레임워크가 따르는 원칙 가이드는 다음과 같습니다.

* 모든 단계에서 선택을 제공합니다. 스프링은 가능한 한 나중에 디자인을 결정할 수 있도록 미룰 수 있습니다.
예를 들어, 코드를 변경하지 않고 구성(configuration)을 통해 영속성 공급자를 변경할 수 있습니다.
마찬가지로 다양한 인프라 관련 문제와 써드파티 API와의 통합에도 동일하게 적용됩니다.
* 다양한 관점을 수용합니다. 스프링은 유연하고 어떻게 해야 하는지에 대해 강제하지 않습니다.
이는 다양한 관점에서 애플리케이션의 많은 요구사항을 지원할 수 있습니다.
* 강력한 하위 호환성을 유지합니다. 스프링은 버전 간의 변경이 서로 충돌나지 않도록 조심스럽게 발전해왔습니다.
스프링은 신중하게 선택된 JDK와 써드 파티 라이브러리 버전 범위를 지원하여 스프링에 의존하는
애플리케이션과 라이브러리의 유지보수가 용이하게 해줍니다.
* API 디자인을 중요하게 생각합니다. 스프링 팀은 직관적이고 오랜 기간 동안 많은 버전에서 유지되는
API를 만들기 위해 많은 고민을 하고 시간을 투자합니다.
* 높은 코드 품질을 유지합니다. 스프링 프레임워크는 의미있고, 최신이며 정확한 javadoc에 중요성을 크게 두고 있습니다.
이는 패키지 간에 순환 의존성이 없는 클린 코드 구조를 가진 몇 안되는 프로젝트 중 하나입니다.




[[overview-feedback]]
== Feedback and Contributions
== 피드백과 기여

질문, 진단 또는 디버깅 이슈에 대해서는 Stack Overflow를 사용하는 것을 권장합니다.
Stack Overflow에서 사용할 태그 목록을 보려면 여기를 클릭하세요. Click {stackoverflow-spring-tag}+or+spring-mvc+or+spring-aop+or+spring-jdbc+or+spring-r2dbc+or+spring-transactions+or+spring-annotations+or+spring-jms+or+spring-el+or+spring-test+or+spring+or+spring-orm+or+spring-jmx+or+spring-cache+or+spring-webflux+or+spring-rsocket?tab=Newest[here]
스프링 프레임워크에 꽤 확실한 문제가 있거나, 기능을 제안하고 싶다면 {spring-framework-issues}[GitHub Issues]를 사용하세요.

만약 해결책이나 제안할 수정 사항이 있다면, {spring-framework-github}[Github] 여기서 Pull Request를 보낼 수 있습니다.
매우 사소한 문제를 제외하고는, 이슈 트래커에 등록 후, 토론을 진행하고 나중에 참고할 수 있도록 기록을 남겨두고 있다는 것을 기억하세요.

좀 더 자세한 가이드라인은 {spring-framework-code}/CONTRIBUTING.md[CONTRIBUTING] 여기 있는 최상위 프로젝트 페이지를 참고하세요.


[[overview-getting-started]]
== 시작하기

스프링을 처음 시작하는 경우, 스프링 부트 기반 애플리케이션을 생성하여 스프링 프레임워크를 사용하기 시작하는 것이 좋습니다.
스프링 부트는 프로덕션에 적합한 스프링 기반 애플리케이션을 빠르게(그리고 스프링 부트가 추천한 방식으로) 만드는 방법을 제공합니다.
이는 스프링 프레임워크를 기반으로 하며, 설정보다는 컨벤션을 선호하고, 가능한 빠르게 시작할 수 있도록 설계되었습니다.

기본 프로젝트를 만들기 위해서는 https://start.spring.io/[start.spring.io]를 사용하거나
{spring-site-guides}/gs/rest-service/[Getting Started Building a RESTful Web Service]와 같은
{spring-site-guides}["Getting Started" guides]를 따라할 수 있습니다.
이 가이드는 이해하기 쉽고, 개발 작업에 매우 집중하기 좋습니다. 또한, 대부분 스프링 부트를 기반으로 하고 있습니다.
이 가이드는 스프링 포트폴리오의 다른 프로젝트들도 다루고 있으므로, 특정 문제를 해결할 때 이를 사용할 수 있습니다.